name = "fncsdraft-mp"
main = "src/worker.js"
compatibility_date = "2026-08-26"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "Lobby"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Lobby"]
