// Who is at the Reload Elite Series Championship, and how the forty seats fill.
//
// The rules decide it off each cup's Finals leaderboard: Europe sends its top
// three, NA Central two, and Oceania, Asia, the Middle East, Brazil and NA West
// one each — ten a cup, forty in all. A duo cannot hold two seats, so a repeat
// winner's second seat passes down that same leaderboard.
//
// Two sources, both harvested:
//   - Europe and all of cup 4 from Epic's payload / the saved Tracker pages,
//     via tools/ewc-rows.generated.js and ~/Desktop/ewc/api
//   - cups 1-3 outside Europe from Tracker's payload, read in a browser tab and
//     kept in ~/Desktop/ewc/regions-finals.txt
//
//   node tools/build-ewc-lan.js                       # print the field
//   node tools/build-ewc-lan.js tools/ewc-lan.generated.js
const fs = require('fs'), path = require('path');

const HOME = process.env.USERPROFILE || process.env.HOME;
const SRC = process.env.EWC_SRC || path.join(HOME, 'Desktop', 'ewc');
const OUT = process.argv[2] || null;

// Attachment: how many seats a region takes from each cup.
const SEATS = {EU: 3, NAC: 2, NAW: 1, BR: 1, OCE: 1, ASIA: 1, ME: 1};
const REGIONS = Object.keys(SEATS);

// ---- Europe, out of the rows the mode already ships ------------------------
const rowsFile = fs.readFileSync(path.join(__dirname, 'ewc-rows.generated.js'), 'utf8');
const { EWC_RAW } = new Function(rowsFile + '; return {EWC_RAW};')();
// Every region's final, straight out of the rows the mode ships — which since
// the circuit was harvested whole is all seven of them, so there is nothing
// left to read out of a side file.
const finals = {};
[1, 2, 3, 4].forEach(cup => {
  const byRegion = EWC_RAW['r' + cup] || {};
  Object.keys(byRegion).forEach(reg => {
    const f = byRegion[reg].final || [];
    if (!f.length) return;
    (finals[reg] = finals[reg] || {})[cup] = f.map(r => ({
      rank: r[0], pts: r[1], matches: r[2], wins: r[3],
      avgElims: r[4], avgPlace: r[5], duo: r.slice(7)}));
  });
});

// ---- the seats ------------------------------------------------------------
const key = duo => duo.map(h => String(h).trim().toLowerCase()).sort().join('|');
const held = new Set();
const field = [];
const shortfall = [];
for (const cup of [1, 2, 3, 4]) {
  for (const reg of REGIONS) {
    const table = (finals[reg] || {})[cup] || [];
    let taken = 0, passed = 0;
    for (const row of table) {
      if (taken >= SEATS[reg]) break;
      if (!row.duo.length) continue;
      // A duo already going to Riyadh cannot take a second seat; it falls to
      // the next team on the same leaderboard.
      if (held.has(key(row.duo))) { passed++; continue; }
      held.add(key(row.duo));
      field.push({cup, region: reg, seat: taken + 1, passedTo: passed, ...row});
      taken++;
    }
    if (taken < SEATS[reg]) shortfall.push('cup ' + cup + ' ' + reg + ': ' + taken + ' of ' + SEATS[reg] +
      (table.length ? ' (leaderboard ran out after ' + table.length + ' rows)' : ' (no leaderboard harvested)'));
  }
}

console.log('The Reload Elite Series Championship — Riyadh, 18-21 August 2026\n');
console.log('cup  region  seat  duo                                    points  wins');
field.forEach(f => console.log('  ' + f.cup + '   ' + f.region.padEnd(6) + '  #' + f.seat + '    ' +
  f.duo.join(' & ').padEnd(38) + String(f.pts).padStart(5) + String(f.wins).padStart(6) +
  (f.passedTo ? '   (passed down ' + f.passedTo + ')' : '')));
console.log('\n' + field.length + ' of 40 seats filled, ' + new Set(field.map(f => f.region)).size + ' regions');
if (shortfall.length) console.log('short:\n  ' + shortfall.join('\n  '));

if (OUT) {
  const body = 'const EWC_LAN=' + JSON.stringify(field.map(f => [f.cup, f.region, f.rank, f.pts,
    f.matches, f.wins, f.avgElims, f.avgPlace].concat(f.duo))) + ';\n';
  fs.writeFileSync(OUT, '// Generated by tools/build-ewc-lan.js — do not edit by hand.\n' +
    '// [cup, region, rank in that final, points, matches, wins, avgElims, avgPlace, ...duo]\n' + body);
  console.log('\nwrote ' + OUT);
}
